### ISSUE TITLE
Adding Water and Ice Textures

### ISSUE THREAD

**Issue by DJSR59** [AnthonyTornetta/Cosmos#151]
Adding Water and Ice Textures

**Comment by DJSR59** [comment]
On Ice blocks, make the sides textures a bit spikier to create a more "glacial" feel. There should be two different ice blocks, one for glaciers and one for oceans. The ocean blocks should have a smoother look. This can be created when transparency is worked on.

**Comment by AnthonyTornetta** [comment]
Merged in https://github.com/AnthonyTornetta/Cosmos/pull/164
